# Generated by Django 5.2.17 on 2026-09-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        help_text="Anonymous session association for continuity; not verified identity.",
                        max_length=128,
                        verbose_name="session key",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("pt-br", "Portuguese (Brazil)")],
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("failed", "Failed")],
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "conversation",
                "verbose_name_plural": "conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Deterministic order within the conversation.",
                        verbose_name="sequence",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.conversation",
                        verbose_name="conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversation message",
                "verbose_name_plural": "conversation messages",
                "ordering": ["conversation", "sequence"],
                "unique_together": {("conversation", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="SourceEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rank", models.PositiveIntegerField(verbose_name="retrieval rank")),
                (
                    "distance",
                    models.FloatField(blank=True, null=True, verbose_name="retrieval distance"),
                ),
                (
                    "document_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="document title snapshot"
                    ),
                ),
                (
                    "document_slug",
                    models.SlugField(
                        blank=True, max_length=200, verbose_name="document slug snapshot"
                    ),
                ),
                (
                    "document_language",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="document language snapshot"
                    ),
                ),
                (
                    "document_category",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="document category snapshot"
                    ),
                ),
                (
                    "chunk_content",
                    models.TextField(blank=True, verbose_name="chunk content snapshot"),
                ),
                (
                    "retrieved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="retrieved at"),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="knowledge.knowledgechunk",
                        verbose_name="knowledge chunk",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="knowledge.knowledgedocument",
                        verbose_name="knowledge document",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_evidence",
                        to="assistant.conversationmessage",
                        verbose_name="assistant message",
                    ),
                ),
            ],
            options={
                "verbose_name": "source evidence",
                "verbose_name_plural": "source evidence",
                "ordering": ["message", "rank"],
            },
        ),
    ]
