# Generated by Django 5.2.17 on 2026-08-31 01:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'page view'), ('project_interaction', 'project interaction'), ('resume_cta', 'résumé CTA'), ('contact_cta', 'Contact CTA'), ('contact_success', 'successful Contact submission'), ('language_change', 'language change'), ('professional_link', 'professional link')], max_length=32, verbose_name='event type')),
                ('path', models.CharField(max_length=255, verbose_name='path')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='language')),
                ('session_fingerprint', models.CharField(blank=True, help_text='SHA-256 hash of the Django session key; no PII is stored.', max_length=64, verbose_name='session fingerprint')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'analytics event',
                'verbose_name_plural': 'analytics events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='common_anal_event_t_6bd2d8_idx'), models.Index(fields=['path', 'created_at'], name='common_anal_path_62badf_idx')],
            },
        ),
    ]
