# Generated by Django 5.2.17 on 2026-08-31 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticsevent",
            name="session_fingerprint",
        ),
    ]
