# Generated by Django 5.2.17 on 2026-08-10 15:22

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'full_name',
                    models.CharField(max_length=100, verbose_name='Full name'),
                ),
                (
                    'email',
                    models.EmailField(max_length=254, verbose_name='Email address'),
                ),
                (
                    'subject',
                    models.CharField(max_length=150, verbose_name='Subject'),
                ),
                (
                    'message',
                    models.TextField(max_length=4000, verbose_name='Message'),
                ),
                (
                    'communication_type',
                    models.CharField(
                        choices=[
                            ('contact', 'Contact'),
                            ('quotation', 'Quotation request'),
                        ],
                        default='contact',
                        max_length=16,
                        verbose_name='Communication type',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('received', 'Received'),
                            ('notified', 'Notified'),
                            ('notification_failed', 'Notification failed'),
                        ],
                        default='received',
                        max_length=32,
                        verbose_name='Processing status',
                    ),
                ),
                (
                    'submitted_at',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='Submitted at',
                    ),
                ),
            ],
            options={
                'verbose_name': 'contact request',
                'verbose_name_plural': 'contact requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
