# Generated by Django 5.2.17 on 2026-08-31 21:43

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="slug")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("pt-br", "Portuguese (Brazil)")],
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROFILE", "Profile"),
                            ("EXPERIENCE", "Experience"),
                            ("SKILL", "Skill"),
                            ("PROJECT", "Project"),
                            ("ENGINEERING", "Engineering"),
                            ("PROCESS", "Process"),
                            ("PORTFOLIO", "Portfolio"),
                            ("GENERAL", "General"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "indexing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("indexing", "Indexing"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="indexing status",
                    ),
                ),
                (
                    "index_version",
                    models.PositiveIntegerField(default=1, verbose_name="index version"),
                ),
                (
                    "embedding_model",
                    models.CharField(blank=True, max_length=128, verbose_name="embedding model"),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="indexed at"),
                ),
                ("last_index_error", models.TextField(blank=True, verbose_name="last index error")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "knowledge document",
                "verbose_name_plural": "knowledge documents",
                "ordering": ["-updated_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="sequence")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=1024, verbose_name="embedding"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.knowledgedocument",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "knowledge chunk",
                "verbose_name_plural": "knowledge chunks",
                "ordering": ["document", "sequence"],
                "unique_together": {("document", "sequence")},
            },
        ),
    ]
